name: localization-updater
description: "some description"
runs-on: ubuntu-latest
branding: 
  color: gray-dark
  icon: archive
inputs: 
  localization_api_host:
    description: "the localization-api host to be called for getting translations"
    required: true
  translation_format: 
    description: "format: flat or levels"
    required: true
  translation_folder:
    description: "folder where translation files must be created"
    required: true
  translation_filename:
    default: auto_gen_translations.json
    description: "name of the translation file to be created (aplies only for single translation file)"
  individual_locale_files:
    default: false
    description: "whether to create one file per locale or a single file with all locales"
  branch_prefix:
    default: auto_gen_translations
    description: "the name of the branch with new translation files"
  commit_changes:
    default: true
    description: "whether to commit the new translations files to the git repository or not"
  create_branch: 
    default: true
    description: "whether to create a new branch with translations or not"
  namespace:
    description: "the translations namespace in localization service"
    required: true
  feature:
    description: "the feature to be get from the translation keys"
    required: true
runs: 
  using: composite
  steps:
    - name: "Get translations"
      id: pr
      run: chmod +x "${{ github.action_path }}/scripts/gettranslations.sh" && "${{ github.action_path }}/scripts/gettranslations.sh" -h '${{ inputs.localization_api_host }}' -f '${{ inputs.translation_format }}' -d '${{ inputs.translation_folder }}' -i '${{ inputs.individual_locale_files }}' -n '${{ inputs.translation_filename }}' -p '${{ inputs.branch_prefix }}' -c '${{ inputs.commit_changes }}' -b '${{ inputs.create_branch }}' -s '${{ inputs.namespace }}' -e '${{ inputs.feature }}'
      shell: bash
