name: localization-updater
description: "some description"
runs-on: ubuntu-latest
branding: 
  color: gray-dark
  icon: archive
inputs: 
  localization_api_host:
    description: "the localization-api host to be called for getting translations"
    required: true
  translation_format: 
    description: "format: flat or levels"
    required: true
  translation_folder:
    description: "folder where translation files must be created"
    required: true
  translation_folder_overwrite:
    description: "whether to overwrite pre-existing translations folder or not"
    default: false
  translation_filename:
    default: auto_gen_translations.json
    description: "name of the translation file to be created (aplies only for single translation file)"
  individual_locale_files:
    default: false
    description: "whether to create one file per locale or a single file with all locales"
  branch_prefix:
    default: auto_gen_translations
    description: "the name of the branch with new translation files"
  commit_changes:
    default: true
    description: "whether to commit the new translations files to the git repository or not"
  commit_message:
    description: "a commit message"
    required: false
  create_branch: 
    default: true
    description: "whether to create a new branch with translations or not"
  main_branch_name:    
    default: master
    description: "the name of the main branch. Default name is master"
  namespace:
    description: "the translations namespace in localization service"
    required: true
  feature:
    description: "the feature to be get from the translation keys"
    required: true
  separator:
    description: "a character or string to be used as separator of the parts of the keys"
    required: false
  omit_key_first_level:
    description: "whether to omit the first part of the key name, which is specified in the feature parameter, or not"
    required: false
  on_error_bypass:
    description: "Whether to finish the execution of the script with success, even it fails, or not"
    required: false
runs: 
  using: composite
  steps:
    - name: "Get translations"
      id: pr
      run: chmod +x "${{ github.action_path }}/scripts/gettranslations.sh" && "${{ github.action_path }}/scripts/gettranslations.sh" -h '${{ inputs.localization_api_host }}' -f '${{ inputs.translation_format }}' -d '${{ inputs.translation_folder }}' -r '${{ inputs.translation_folder_overwrite }}' -i '${{ inputs.individual_locale_files }}' -n '${{ inputs.translation_filename }}' -p '${{ inputs.branch_prefix }}' -c '${{ inputs.commit_changes }}' -o '${{ inputs.commit_message }}' -b '${{ inputs.create_branch }}' -m '${{ inputs.main_branch_name }}' -s '${{ inputs.namespace }}' -e '${{ inputs.feature }}' -t '${{ inputs.separator }}' -l '${{ inputs.omit_key_first_level }}'
      shell: bash
